
spring:
  application:
    name: timesheet
  datasource:
    url: jdbc:mysql://localhost:60001/timesheet?useLegacyDatetimeCode=false&serverTimezone=America/Sao_Paulo
    password: timesheet
    username: timesheet
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  messages:
    basename: locale/messages
    encoding: windows-1252
  security:
    user:
      name: timesheet
      password: timesheet
      roles: manager

hibernate:

logging:
  level:
    br.com.driw.timesheet.modules: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
